// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var V2Component$ReactHooksTemplate = require("./V2Component.bs.js");
var V3Component$ReactHooksTemplate = require("./V3Component.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, V2Component$ReactHooksTemplate.make("Hello V2!", /* array */[])), "v2-root");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, V3Component$ReactHooksTemplate.Jsx2[/* make */1]("Hello V3!", /* array */[])), "v3-root");

/*  Not a pure module */
